# Generated by Django 4.0.1 on 2022-01-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_question_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d'),
        ),
    ]
