# Generated by Django 4.0.1 on 2022-01-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_question_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
    ]
