# Generated by Django 3.2.5 on 2022-01-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_question_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qsolve',
            field=models.IntegerField(default='0'),
        ),
    ]
