# Generated by Django 3.2.5 on 2022-01-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_question_qsolve'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='writer',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
