# Generated by Django 4.0.1 on 2022-01-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_question_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code_edit',
            field=models.TextField(blank=True),
        ),
    ]
