# Generated by Django 3.2.5 on 2022-01-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField()),
                ('userid', models.CharField(max_length=50)),
                ('repository', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
