# Generated by Django 3.2.5 on 2022-01-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220124_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('html_url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
            ],
        ),
    ]
