# Generated by Django 3.2.5 on 2022-01-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_githubuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='userid',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='avatar',
            field=models.CharField(max_length=200),
        ),
    ]
