# Generated by Django 3.2.5 on 2022-01-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220126_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='avatar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='blog',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
