# Generated by Django 3.2.5 on 2022-01-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220126_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='eventid',
            field=models.CharField(max_length=50),
        ),
    ]
